### ISSUE TITLE
Kill all child processes of any process being targeted by Rewind.

### ISSUE THREAD

**Issue by 247arjun** [Neo23x0/Rewind#1]
[Process.Kill(Boolean)](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.kill?view=net-5.0#System_Diagnostics_Process_Kill_System_Boolean_) allows the termination of all child processes created by a given process. Given that malware has a tendency to not persist as a single process, and likes to spawn new processes, this will be more effective at killing the process tree.

**Comment by Neo23x0** [comment]
My Visual Studio shows an error whenever I want to use a Boolean param. 
![Screenshot 2021-03-27 173327](https://user-images.githubusercontent.com/2851492/112727381-910adb80-8f22-11eb-9ad9-e7c34b16b32c.png)

**Comment by Neo23x0** [comment]
Ah, it's lowercase `true`
