### ISSUE TITLE
Check Process.HasExited before confirming that a process has been terminated.

### ISSUE THREAD

**Issue by 247arjun** [Neo23x0/Rewind#2]
Currently, Rewind confirms that a process is being killed before the `.Kill()` call is made. 

It might be better to call `.Kill()`, and then check if [`proc.HasExited`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.hasexited?view=net-5.0) is `True`, to see if the process has been terminated.

**Comment by Neo23x0** [comment]
Fixed thanks https://github.com/Neo23x0/Rewind/commit/9400256f444398fce40532b05d97a593aaed91e7

**Comment by 247arjun** [comment]
I have seen proc.HasExited throw an exception (don't remember which), so some additional testing may be necessary to ensure that is being handled when thrown.
